### ISSUE TITLE
Error listing directory

### ISSUE THREAD

**Issue by githubxnoob** [garethflowers/docker-ftp-server#67] opened 2023-10-12 06:36 UTC
its not working in any ftp clients.
the server is running but i get the following error in clients.

```
Timeout detected. (control connection)
Could not retrieve directory listing
Error listing directory '/'.
```

**Comment by FinalTek** [comment] 2023-12-06 20:55
same error

**Comment by kongkx** [comment] 2023-12-23 03:48
maybe related to `pasv_address=0.0.0.0` . 

FYI

https://stackoverflow.com/questions/43758580/filezilla-the-data-connection-could-not-be-established-econnrefused-connec

**Comment by rogervdf** [comment] 2024-01-21 22:09
I can confirm that the `pasv_address` is the problem when behind a NAT or routing otherwise

For my own purposes I hotfixed the problem with a Dockerfile as follows..

```
FROM garethflowers/ftp-server

RUN sed -i -r "s/0.0.0.0/my_external_ip/g" /etc/vsftpd.conf
```

...and then running this newly tagged/built container instead

it would be better to create an ENV variable somehow to set this variable in an easier way

**Comment by scolbeck** [comment] 2024-01-31 14:58
I also had a problem due to `pasv_address=0.0.0.0` being set by default.  My containers are in a VLAN and my security cameras created 0 size files because of this.  However I also had to remove the `pasv_addr_resolve=YES` line as well as I think that was setting it to expect a hostname instead of an IP address.
```
FROM garethflowers/ftp-server:0.7

RUN sed -i -r "s/0.0.0.0/192.168.1.5/g" /etc/vsftpd.conf && sed -i "/pasv_addr_resolve/d" /etc/vsftpd.conf
```

**Comment by garethflowers** [comment] 2024-11-24 16:59
Duplicate of #14.

**Closed by garethflowers** 2024-11-24 16:59 UTC
Labels: duplicate
